server:
  error:
    include-stacktrace: ON_TRACE_PARAM

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:12.2-alpine:///michalkowol
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    WireMock: WARN
    com.michalkowol: INFO
#    org.springframework.transaction: DEBUG
#    org.springframework.orm.jpa: DEBUG
