spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:12.2-alpine:///michalkowol
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
